add file response formatter
endpointuz/service-request-helper-lib pull request #2
Opened 2024-02-15 15:47 UTC by Sarvar-K

Я не нашел никакой подходящей обертки над респосом или байтами, поэтому создал свою.

Ридми дополню в отдельном пулл реквесте после аппрува этого.

2024-02-15 15:55 UTC, Sarvar-K commented on servic_request_helper/types.py
> +        self.filename = get_filename_from_content_disposition_header(content_disposition)
более простого способа получить название файла не нашлось

2024-02-15 15:55 UTC, Sarvar-K commented on servic_request_helper/types.py
> +        self.filename = get_filename_from_content_disposition_header(content_disposition)
получать название файла из контента я тоже пробовал

2024-02-16 07:31 UTC, ksinn commented on servic_request_helper/types.py
> +        self.filename = get_filename_from_content_disposition_header(content_disposition)
так его та ми нет. это стандартный способ передачи названия файла для респонса))))

2024-02-16 07:41 UTC, ksinn requested changes
Представь что когда нибудь за каким то хером нам понадобится обрабатывать респонс  в формате multipart-form-data. Нам возможно было бы ухобно вернуть его в формате дикта, где поля с файлами будут иметь значения таких же обьектв, как когда мы получаем файл из обычного ответа, то есть инстанс ResponseFile. 
мы сможем это сделать с дописыванием нового кода и без редактирвоания старого?

2024-02-16 07:41 UTC, ksinn commented on servic_request_helper/types.py
> +            self.extension = content_type_list[1] or None
ты прям уверен уверне в этом подходе?

2024-02-16 10:51 UTC, Sarvar-K commented on servic_request_helper/utils.py
> +    return msg.get_content_maintype(), msg.get_content_subtype()
Если значение контент тайпа не будет соответствовать стандарту (https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types#structure_of_a_mime_type), то функция вернет (text, plain),
так как ответ на http запрос это по определению текст

2024-02-16 11:51 UTC, konstantin0488 approved these changes

2024-02-19 09:46 UTC, ksinn requested changes

2024-02-19 09:46 UTC, ksinn commented on servic_request_helper/utils.py
> +    return msg.get_content_maintype(), msg.get_content_subtype()
не надо разбивать мем тайп. это просто негде будет потом использывать.
а если нужно расширение - то или возьми его из названия файла. или по полному мем тайму опредлени с помошью какой нибудь библиотеки

2024-02-20 07:07 UTC, ksinn approved these changes

2024-02-20 07:51 UTC, merged