Feature/tests
endpointuz/service-request-helper-lib pull request #4
Opened 2024-02-22 15:53 UTC by Sarvar-K

2024-02-23 07:32 UTC, konstantin0488 approved these changes

2024-02-23 07:43 UTC, ksinn requested changes

2024-02-23 07:43 UTC, ksinn commented on test/test_async_response_formatters.py
> +            })
вот в этом тест кейсе ты по ситу проверяешьправельность заоплнения своего мока)))

2024-02-26 09:22 UTC, ksinn approved these changes

2024-02-26 09:22 UTC, ksinn commented on test/test_async_response_formatters.py
> +        self.assertEqual(self.mock_response.__hash__(), formatted_mock_response.__hash__())
эммм а ты же в курсе, что поидее все что начинается с _ и __ - это типо приватное?

2024-02-26 11:54 UTC, merged